#!/usr/bin/env bash
set -euo pipefail

# OpenResiApp — Quick Setup Script
# Generates .env and docker-compose.yml for production deployment

echo ""
echo "  OpenResiApp — Setup"
echo "  ==================="
echo ""

# Check for required tools
if ! command -v openssl &> /dev/null; then
  echo "Error: openssl is required to generate secrets."
  echo "Install it and try again."
  exit 1
fi

if ! command -v docker &> /dev/null; then
  echo "Error: docker is required to run OpenResiApp."
  echo "Install Docker: https://docs.docker.com/engine/install/"
  exit 1
fi

# Collect input
read -rp "Your domain (e.g. dom.example.sk): " APP_DOMAIN
if [[ -z "$APP_DOMAIN" ]]; then
  echo "Error: Domain is required."
  exit 1
fi

read -rp "Building name (e.g. Bytove spolocenstvo Hlavna 12): " APP_NAME
APP_NAME="${APP_NAME:-Bytove spolocenstvo}"

read -rp "Language — sk or en [sk]: " LANGUAGE
LANGUAGE="${LANGUAGE:-sk}"

if [[ "$LANGUAGE" != "sk" && "$LANGUAGE" != "en" ]]; then
  echo "Error: Language must be 'sk' or 'en'."
  exit 1
fi

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)
NEXTAUTH_SECRET=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)

APP_URL="https://${APP_DOMAIN}"

# Write .env
if [[ -f ".env" ]]; then
  read -rp ".env already exists. Overwrite? [y/N]: " OVERWRITE
  if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
    echo "Aborted. Existing .env was not changed."
    exit 0
  fi
fi

cat > .env <<EOF
# OpenResiApp — generated by setup.sh on $(date +%Y-%m-%d)
APP_NAME="${APP_NAME}"
APP_URL=${APP_URL}
APP_DOMAIN=${APP_DOMAIN}
LANGUAGE=${LANGUAGE}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
EOF

chmod 600 .env

# Write docker-compose.yml if it doesn't exist
if [[ ! -f "docker-compose.yml" ]]; then
  cat > docker-compose.yml <<'COMPOSE'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: resiapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ipk0/open-resiapp:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/resiapp
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${APP_URL}
      AUTH_TRUST_HOST: "true"
      APP_NAME: ${APP_NAME:-Bytove spolocenstvo}
      LANGUAGE: ${LANGUAGE:-sk}
    volumes:
      - uploads:/app/uploads

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    depends_on:
      - app
    command: caddy reverse-proxy --from ${APP_DOMAIN} --to app:3000

volumes:
  postgres_data:
  uploads:
  caddy_data:
COMPOSE
  echo "Created docker-compose.yml"
fi

echo ""
echo "  Setup complete!"
echo "  ==============="
echo ""
echo "  Domain:   ${APP_URL}"
echo "  Building: ${APP_NAME}"
echo "  Language: ${LANGUAGE}"
echo ""
echo "  Secrets generated and saved to .env"
echo ""
echo "  Next steps:"
echo ""
echo "    1. Start the app:"
echo "       docker compose up -d"
echo ""
echo "    2. Create your admin account:"
echo "       docker compose exec app npx tsx src/scripts/create-admin.ts \\"
echo "         --email admin@${APP_DOMAIN} --name \"Your Name\""
echo ""
echo "    3. Open https://${APP_DOMAIN} in your browser"
echo ""
echo "  To update later:"
echo "    docker compose pull && docker compose up -d"
echo ""