// BYT-20260515-001 Phase 1a: per-instance kind catalog.
// Client-safe types + slug constants. Server-only operations
// (DB seed, lookup against entity_kinds table) live in
// registry.server.ts.

export const CANONICAL_KIND_SLUGS = [
  // Residential & housing
  "community",
  "building",
  "entrance",
  "unit",
  "house",
  "street",
  "cottage",
  "mobile_home_pad",
  // Land & nature
  "garden_section",
  "plot",
  "parcel_group",
  "parcel",
  "apiary_zone",
  "hive_owner",
  "hunting_district",
  "hunter",
  "pond",
  "license_holder",
  // Commercial & shared
  "garage_block",
  "garage",
  "storage_row",
  "storage_unit",
  "floor",
  "office_suite",
  "coworking_zone",
  "desk",
  "industrial_block",
  "tenant_lot",
  "dock",
  "mooring",
  // Social & civic
  "club_section",
  "member_locker",
  "class",
  "parent_seat",
  "congregation_group",
  "member_household",
  "cemetery_section",
  "grave_plot",
  // Generic fallback
  "generic_group",
] as const;

export type CanonicalKindSlug = (typeof CANONICAL_KIND_SLUGS)[number];

// Legacy enum (entityKindEnum in src/db/schema.ts) → new slug.
// Used by Phase 1b backfill to populate entity_kinds + rewrite
// entities.kind from enum to text FK. Once Phase 1b lands, the
// enum disappears and this map becomes a one-off migration artifact.
export const LEGACY_KIND_TO_SLUG = {
  housing_community: "community",
  housing_block: "building",
  housing_entrance: "entrance",
  housing_unit: "unit",
  generic_group: "generic_group",
} as const satisfies Record<string, CanonicalKindSlug>;

export type LegacyKind = keyof typeof LEGACY_KIND_TO_SLUG;

export interface KindCatalogRow {
  slug: string;
  displayNameKey: string;
  icon: string | null;
  allowsMembers: boolean;
  votable: boolean;
  allowedParentKinds: string[];
  dataSchema: Record<string, unknown>;
  sortOrder: number;
}

// BYT-20260515-001 Phase 5: canonical kind catalog covering every
// entity kind used by any v1 template. The bootstrap script reads the
// template's required kinds (root_kind + import_levels + starter_tree
// kinds) and seeds only those rows so an instance's `entity_kinds`
// table stays scoped to what its template needs.
//
// Each entry is conservative: minimal `data_schema`, no opinion on
// allowed_parent_kinds beyond what the v1 templates exercise. Custom
// kinds added via UI later may relax these.
export const CANONICAL_KIND_CATALOG: KindCatalogRow[] = [
  // Root — used by every template
  {
    slug: "community",
    displayNameKey: "Kinds.community",
    icon: "building-2",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: [],
    dataSchema: {},
    sortOrder: 10,
  },
  // Residential & housing
  {
    slug: "building",
    displayNameKey: "Kinds.building",
    icon: "building",
    allowsMembers: false,
    votable: false,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 20,
  },
  {
    slug: "entrance",
    displayNameKey: "Kinds.entrance",
    icon: "door-open",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community", "building"],
    dataSchema: {},
    sortOrder: 30,
  },
  {
    slug: "unit",
    displayNameKey: "Kinds.unit",
    icon: "home",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["entrance", "building", "community"],
    dataSchema: {
      type: "object",
      properties: {
        flat_number: { type: "string" },
        floor: { type: "integer" },
        share_numerator: { type: "integer" },
        share_denominator: { type: "integer" },
        area_m2: { type: "number" },
      },
    },
    sortOrder: 40,
  },
  {
    slug: "house",
    displayNameKey: "Kinds.house",
    icon: "home",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["street", "community"],
    dataSchema: {},
    sortOrder: 50,
  },
  {
    slug: "street",
    displayNameKey: "Kinds.street",
    icon: "milestone",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 60,
  },
  {
    slug: "cottage",
    displayNameKey: "Kinds.cottage",
    icon: "tent",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["garden_section", "community"],
    dataSchema: {},
    sortOrder: 70,
  },
  {
    slug: "mobile_home_pad",
    displayNameKey: "Kinds.mobile_home_pad",
    icon: "caravan",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["garden_section", "community"],
    dataSchema: {},
    sortOrder: 80,
  },
  // Land & nature
  {
    slug: "garden_section",
    displayNameKey: "Kinds.garden_section",
    icon: "trees",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 90,
  },
  {
    slug: "plot",
    displayNameKey: "Kinds.plot",
    icon: "sprout",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["garden_section", "community"],
    dataSchema: {},
    sortOrder: 100,
  },
  {
    slug: "parcel_group",
    displayNameKey: "Kinds.parcel_group",
    icon: "layers",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 110,
  },
  {
    slug: "parcel",
    displayNameKey: "Kinds.parcel",
    icon: "land-plot",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["parcel_group", "community"],
    dataSchema: {
      type: "object",
      properties: {
        share_numerator: { type: "integer" },
        share_denominator: { type: "integer" },
        area_m2: { type: "number" },
      },
    },
    sortOrder: 120,
  },
  {
    slug: "apiary_zone",
    displayNameKey: "Kinds.apiary_zone",
    icon: "map",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 130,
  },
  {
    slug: "hive_owner",
    displayNameKey: "Kinds.hive_owner",
    icon: "bug",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["apiary_zone", "community"],
    dataSchema: {},
    sortOrder: 140,
  },
  {
    slug: "hunting_district",
    displayNameKey: "Kinds.hunting_district",
    icon: "map",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 150,
  },
  {
    slug: "hunter",
    displayNameKey: "Kinds.hunter",
    icon: "user",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["hunting_district", "community"],
    dataSchema: {},
    sortOrder: 160,
  },
  {
    slug: "pond",
    displayNameKey: "Kinds.pond",
    icon: "fish",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 170,
  },
  {
    slug: "license_holder",
    displayNameKey: "Kinds.license_holder",
    icon: "user",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["pond", "community"],
    dataSchema: {},
    sortOrder: 180,
  },
  // Commercial & shared
  {
    slug: "garage_block",
    displayNameKey: "Kinds.garage_block",
    icon: "warehouse",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 190,
  },
  {
    slug: "garage",
    displayNameKey: "Kinds.garage",
    icon: "car",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["garage_block", "community"],
    dataSchema: {},
    sortOrder: 200,
  },
  {
    slug: "storage_row",
    displayNameKey: "Kinds.storage_row",
    icon: "rows-3",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 210,
  },
  {
    slug: "storage_unit",
    displayNameKey: "Kinds.storage_unit",
    icon: "package",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["storage_row", "community"],
    dataSchema: {},
    sortOrder: 220,
  },
  {
    slug: "floor",
    displayNameKey: "Kinds.floor",
    icon: "layers",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["building", "community"],
    dataSchema: {},
    sortOrder: 230,
  },
  {
    slug: "office_suite",
    displayNameKey: "Kinds.office_suite",
    icon: "briefcase",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["floor", "building", "community"],
    dataSchema: {
      type: "object",
      properties: {
        share_numerator: { type: "integer" },
        share_denominator: { type: "integer" },
        area_m2: { type: "number" },
      },
    },
    sortOrder: 240,
  },
  {
    slug: "coworking_zone",
    displayNameKey: "Kinds.coworking_zone",
    icon: "users",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 250,
  },
  {
    slug: "desk",
    displayNameKey: "Kinds.desk",
    icon: "monitor",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["coworking_zone", "community"],
    dataSchema: {},
    sortOrder: 260,
  },
  {
    slug: "industrial_block",
    displayNameKey: "Kinds.industrial_block",
    icon: "factory",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 270,
  },
  {
    slug: "tenant_lot",
    displayNameKey: "Kinds.tenant_lot",
    icon: "land-plot",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["industrial_block", "community"],
    dataSchema: {
      type: "object",
      properties: {
        share_numerator: { type: "integer" },
        share_denominator: { type: "integer" },
        area_m2: { type: "number" },
      },
    },
    sortOrder: 280,
  },
  {
    slug: "dock",
    displayNameKey: "Kinds.dock",
    icon: "anchor",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 290,
  },
  {
    slug: "mooring",
    displayNameKey: "Kinds.mooring",
    icon: "sailboat",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["dock", "community"],
    dataSchema: {},
    sortOrder: 300,
  },
  // Social & civic
  {
    slug: "club_section",
    displayNameKey: "Kinds.club_section",
    icon: "users",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 310,
  },
  {
    slug: "member_locker",
    displayNameKey: "Kinds.member_locker",
    icon: "lock",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["club_section", "community"],
    dataSchema: {},
    sortOrder: 320,
  },
  {
    slug: "class",
    displayNameKey: "Kinds.class",
    icon: "graduation-cap",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 330,
  },
  {
    slug: "parent_seat",
    displayNameKey: "Kinds.parent_seat",
    icon: "user",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["class", "community"],
    dataSchema: {},
    sortOrder: 340,
  },
  {
    slug: "congregation_group",
    displayNameKey: "Kinds.congregation_group",
    icon: "users",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 350,
  },
  {
    slug: "member_household",
    displayNameKey: "Kinds.member_household",
    icon: "home",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["congregation_group", "community"],
    dataSchema: {},
    sortOrder: 360,
  },
  {
    slug: "cemetery_section",
    displayNameKey: "Kinds.cemetery_section",
    icon: "map",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community"],
    dataSchema: {},
    sortOrder: 370,
  },
  {
    slug: "grave_plot",
    displayNameKey: "Kinds.grave_plot",
    icon: "cross",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["cemetery_section", "community"],
    dataSchema: {},
    sortOrder: 380,
  },
  // Generic fallback — supported by every template
  {
    slug: "generic_group",
    displayNameKey: "Kinds.generic_group",
    icon: "folder",
    allowsMembers: false,
    votable: false,
    allowedParentKinds: [
      "community",
      "building",
      "entrance",
      "unit",
      "generic_group",
    ],
    dataSchema: {},
    sortOrder: 999,
  },
];

// Subset that pre-existed as HOA-only — kept exported for backwards
// compatibility (legacy bootstrap paths still reference it). Phase 5
// bootstrap uses CANONICAL_KIND_CATALOG filtered by the template's
// declared kinds.
export const HOA_CATALOG_SEED: KindCatalogRow[] = [
  {
    slug: "community",
    displayNameKey: "Kinds.hoa.community",
    icon: "building-2",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: [],
    dataSchema: {
      type: "object",
      properties: {
        address: { type: "string" },
        ico: { type: "string" },
        voting_method: { enum: ["per_share", "per_flat", "per_area"] },
        country: { enum: ["sk", "cz"] },
        governance_model: {
          enum: ["chairman_council", "committee", "chairman_only"],
        },
      },
      required: ["address"],
    },
    sortOrder: 10,
  },
  {
    slug: "building",
    displayNameKey: "Kinds.hoa.building",
    icon: "building",
    allowsMembers: false,
    votable: false,
    allowedParentKinds: ["community"],
    dataSchema: { type: "object" },
    sortOrder: 20,
  },
  {
    slug: "entrance",
    displayNameKey: "Kinds.hoa.entrance",
    icon: "door-open",
    allowsMembers: false,
    votable: true,
    allowedParentKinds: ["community", "building"],
    dataSchema: { type: "object" },
    sortOrder: 30,
  },
  {
    slug: "unit",
    displayNameKey: "Kinds.hoa.unit",
    icon: "home",
    allowsMembers: true,
    votable: false,
    allowedParentKinds: ["entrance", "building", "community"],
    dataSchema: {
      type: "object",
      properties: {
        flat_number: { type: "string" },
        floor: { type: "integer" },
        share_numerator: { type: "integer" },
        share_denominator: { type: "integer" },
        area_m2: { type: "number" },
      },
      required: ["flat_number", "share_numerator", "share_denominator"],
    },
    sortOrder: 40,
  },
  {
    slug: "generic_group",
    displayNameKey: "Kinds.hoa.genericGroup",
    icon: "folder",
    allowsMembers: false,
    votable: false,
    allowedParentKinds: [
      "community",
      "building",
      "entrance",
      "unit",
      "generic_group",
    ],
    dataSchema: { type: "object" },
    sortOrder: 100,
  },
];
